from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import ListView
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError as DRFValidationError
from rest_framework.response import Response

from apps.accounts.permissions import IsManager, ManagerRequiredMixin

from .models import LowStockAlert
from .serializers import LowStockAlertSerializer
from .services import dismiss_alert, get_active_alerts, sync_low_stock_alerts


class AlertListView(ManagerRequiredMixin, ListView):
    """Alerts aren't in Staff's allowed-actions list at all — Manager-only, full stop."""
    model = LowStockAlert
    template_name = "alerts/alert_list.html"
    context_object_name = "alerts"
    paginate_by = 20

    def get_queryset(self):
        sync_low_stock_alerts()
        if self.request.GET.get("show_dismissed") == "true":
            return LowStockAlert.objects.select_related("item", "dismissed_by")
        return get_active_alerts()


class AlertDismissView(ManagerRequiredMixin, View):
    def post(self, request, pk):
        alert = get_object_or_404(LowStockAlert, pk=pk)
        try:
            dismiss_alert(alert, request.user)
            messages.success(request, f"Alert for {alert.item.sku} dismissed.")
        except ValueError as exc:
            messages.error(request, str(exc))
        return redirect("alert-list")


class LowStockAlertViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Read-only on purpose — alerts are system-generated by sync_low_stock_alerts()
    / sync_alert_for_item(), never user-created, so there is no create/update/
    destroy here at all, only list/retrieve plus the dismiss action.
    """
    serializer_class = LowStockAlertSerializer
    permission_classes = [IsManager]

    def get_queryset(self):
        sync_low_stock_alerts()
        if self.request.query_params.get("show_dismissed") == "true":
            return LowStockAlert.objects.select_related("item", "dismissed_by")
        return get_active_alerts()

    @action(detail=True, methods=["post"])
    def dismiss(self, request, pk=None):
        alert = self.get_object()
        try:
            dismiss_alert(alert, request.user)
        except ValueError as exc:
            raise DRFValidationError(str(exc))
        return Response(LowStockAlertSerializer(alert).data)